// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	auth2 "github.com/bagusyanuar/hris-backend/internal/application/auth"
	"github.com/bagusyanuar/hris-backend/internal/application/employee"
	"github.com/bagusyanuar/hris-backend/internal/application/organization"
	"github.com/bagusyanuar/hris-backend/internal/domain/auth"
	"github.com/bagusyanuar/hris-backend/internal/infrastructure/repository"
	auth3 "github.com/bagusyanuar/hris-backend/internal/interfaces/http/auth"
	employee2 "github.com/bagusyanuar/hris-backend/internal/interfaces/http/employee"
	organization2 "github.com/bagusyanuar/hris-backend/internal/interfaces/http/organization"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeAPI(db *gorm.DB, tokenGen auth.TokenGenerator) (*APIHandlers, error) {
	userRepository := repository.NewUserRepository(db)
	service := auth2.NewService(userRepository, tokenGen)
	handler := auth3.NewHandler(service)
	organizationRepository := repository.NewOrganizationRepository(db)
	organizationService := organization.NewService(organizationRepository)
	organizationHandler := organization2.NewHandler(organizationService)
	employeeRepository := repository.NewEmployeeRepository(db)
	employeeService := employee.NewService(employeeRepository)
	employeeHandler := employee2.NewHandler(employeeService)
	apiHandlers := &APIHandlers{
		Auth:     handler,
		Org:      organizationHandler,
		Employee: employeeHandler,
	}
	return apiHandlers, nil
}

// wire.go:

var RepositorySet = wire.NewSet(repository.NewUserRepository, repository.NewOrganizationRepository, repository.NewEmployeeRepository)

var ServiceSet = wire.NewSet(auth2.NewService, organization.NewService, employee.NewService)

var HandlerSet = wire.NewSet(auth3.NewHandler, organization2.NewHandler, employee2.NewHandler, wire.Struct(new(APIHandlers), "*"))
