// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/bagusyanuar/hris-backend/internal/application/employee"
	"github.com/bagusyanuar/hris-backend/internal/application/organization"
	"github.com/bagusyanuar/hris-backend/internal/auth/application"
	"github.com/bagusyanuar/hris-backend/internal/auth/domain"
	"github.com/bagusyanuar/hris-backend/internal/auth/transport/http"
	"github.com/bagusyanuar/hris-backend/internal/infrastructure/repository"
	employee2 "github.com/bagusyanuar/hris-backend/internal/interfaces/http/employee"
	organization2 "github.com/bagusyanuar/hris-backend/internal/interfaces/http/organization"
	adapter2 "github.com/bagusyanuar/hris-backend/internal/organization/adapter"
	application2 "github.com/bagusyanuar/hris-backend/internal/organization/application"
	http2 "github.com/bagusyanuar/hris-backend/internal/organization/transport/http"
	"github.com/bagusyanuar/hris-backend/internal/user/adapter"
	"github.com/google/wire"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitializeAPI(db *gorm.DB, tokenGen domain.TokenGenerator) (*APIHandlers, error) {
	domainRepository := adapter.NewUserRepository(db)
	service := application.NewService(domainRepository, tokenGen)
	handler := http.NewHandler(service)
	organizationRepository := repository.NewOrganizationRepository(db)
	organizationService := organization.NewService(organizationRepository)
	organizationHandler := organization2.NewHandler(organizationService)
	employeeRepository := repository.NewEmployeeRepository(db)
	employeeService := employee.NewService(employeeRepository)
	employeeHandler := employee2.NewHandler(employeeService)
	companyRepository := adapter2.NewCompanyRepository(db)
	branchRepository := adapter2.NewBranchRepository(db)
	txManager := adapter2.NewGormTxManager(db)
	applicationService := application2.NewService(companyRepository, branchRepository, txManager)
	httpHandler := http2.NewHandler(applicationService)
	apiHandlers := &APIHandlers{
		Auth:         handler,
		Org:          organizationHandler,
		Employee:     employeeHandler,
		Organization: httpHandler,
	}
	return apiHandlers, nil
}

// wire.go:

var RepositorySet = wire.NewSet(adapter.NewUserRepository, repository.NewOrganizationRepository, repository.NewEmployeeRepository, adapter2.NewCompanyRepository, adapter2.NewBranchRepository, adapter2.NewGormTxManager)

var ServiceSet = wire.NewSet(application.NewService, organization.NewService, employee.NewService, application2.NewService)

var HandlerSet = wire.NewSet(http.NewHandler, organization2.NewHandler, employee2.NewHandler, http2.NewHandler, wire.Struct(new(APIHandlers), "*"))
